spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/pan_gyo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123

#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#
#logging:
#  level:
#    org.hibernate.sql: debug

